name: Verifier Analyze
on:
  push:
    branches: [ main ]
    paths:
      - 'verifier/**'
  pull_request:
    paths:
      - 'verifier/**'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: verifier
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2022.3.0

      - name: Deploy Qodana to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./verifier/analysis